# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e77a9ac668d7564b696a7fa7b981648250541922d26978e39b1859ce4f7d7fc80a3f4517f1ccf7b3b26a65fb8b144611aad02fb94bb8a078029043f74a10eaac

test:
  secret_key_base: f8f81223d6a0fe933d07b7d83464801b58fc127384f42dcd3968ecb9770071851ce56af64ea5f339edb5e257813bce1cecadc17351a8bd92dff653f6564207a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
